In [2]:
! pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
df = pd.read_excel('Social_Media_Content_Performance_Dataset.xlsx')
df.head()

,Post_ID,Platform,Content_Type,Content_Category,Post_Type,Region,Longitude,Latitude,Engagement,Views,...,Impressions,Video_Views,Live_Stream_Views,Clicks,Click_Through_Rate,Main_Hashtag,Post_Published_At,Post_Date,Post_Hour,Engagement_Level
0,Post_1,TikTok,Organic,Product Promotion,Video,UK,-3.4360,55.3781,54510,599342,...,677975,465645,0,16813.0,0.0248,#FeatureHighlight,2024-03-14 15:42:00,2024-03-14,15,Low
1,Post_2,Instagram,Organic,Product Promotion,Video,India,78.9629,20.5937,259440,1896301,...,2354474,1896301,0,NaN,NaN,#ProductDemo,2024-04-24 12:02:00,2024-04-24,12,Medium
2,Post_3,X.com,Organic,Entertainment,Text,Brazil,-51.9253,-14.2350,14182,253052,...,304915,0,0,NaN,NaN,#MemeMonday,2024-12-01 10:02:00,2024-12-01,10,Low
3,Post_4,Instagram,Organic,Entertainment,Carousel,Australia,133.7751,-25.2744,49137,735640,...,829727,0,0,NaN,NaN,#JustForFun,2024-07-07 12:59:00,2024-07-07,12,Low
4,Post_5,TikTok,Organic,Educational,Video,Brazil,-51.9253,-14.2350,20832,77358,...,93049,72707,0,1944.0,0.0209,#CaseStudy2025,2024-01-10 11:28:00,2024-01-10,11,High

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5600 entries, 0 to 5599
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Post_ID             5600 non-null   str
 1   Platform            5600 non-null   str
 2   Content_Type        5600 non-null   str
 3   Content_Category    5600 non-null   str
 4   Post_Type           5600 non-null   str
 5   Region              5600 non-null   str
 6   Longitude           5600 non-null   float64
 7   Latitude            5600 non-null   float64
 8   Engagement          5600 non-null   int64
 9   Views               5600 non-null   int64
 10  Likes               5600 non-null   int64
 11  Shares              5600 non-null   int64
 12  Comments            5600 non-null   int64
 13  Engagement_Rate     5600 non-null   float64
 14  Impressions         5600 non-null   int64
 15  Video_Views         5600 non-null   int64
 16  Live_Stream_Views   5600 non-null   int64
 17  Clicks              1860 non-null   float64
 18  Click_Through_Rate  1860 non-null   float64
 19  Main_Hashtag        5600 non-null   str
 20  Post_Published_At   5600 non-null   datetime64[us]
 21  Post_Date           5600 non-null   datetime64[us]
 22  Post_Hour           5600 non-null   int64
 23  Engagement_Level    5600 non-null   str
dtypes: datetime64[us](2), float64(5), int64(9), str(8)
memory usage: 1.0 MB

In [5]:
df.describe()

,Longitude,Latitude,Engagement,Views,Likes,Shares,Comments,Engagement_Rate,Impressions,Video_Views,Live_Stream_Views,Clicks,Click_Through_Rate,Post_Published_At,Post_Date,Post_Hour
count,5600.000000,5600.000000,5.600000e+03,5.600000e+03,5600.000000,5600.000000,5600.000000,5600.000000,5.600000e+03,5.600000e+03,5.600000e+03,1860.000000,1860.000000,5600,5600,5600.000000
mean,9.658511,27.272488,1.154449e+05,8.582634e+05,150720.243571,47684.907679,34515.474286,0.152837,1.029742e+06,6.409677e+05,9.809161e+04,19036.116129,0.018357,2024-08-30 01:14:37.832143,2024-08-29 11:17:03.428571,13.469643
min,-106.346800,-25.274400,7.300000e+01,1.000000e+03,101.000000,32.000000,20.000000,0.050049,1.125000e+03,0.000000e+00,0.000000e+00,12.000000,0.010000,2024-01-01 10:18:00,2024-01-01 00:00:00,8.000000
25%,-95.712900,20.593700,3.700425e+04,2.343490e+05,38544.000000,12104.750000,8589.500000,0.104681,2.805228e+05,0.000000e+00,0.000000e+00,4788.000000,0.014100,2024-04-30 12:10:30,2024-04-30 00:00:00,11.000000
50%,-3.436000,37.090200,5.899150e+04,3.755250e+05,67681.000000,21103.000000,15431.500000,0.154396,4.534145e+05,1.003765e+05,0.000000e+00,8227.000000,0.018150,2024-08-26 10:08:00,2024-08-26 00:00:00,13.000000
75%,78.962900,55.378100,1.534625e+05,1.441124e+06,223101.750000,71295.750000,49196.500000,0.197245,1.718588e+06,1.121694e+06,0.000000e+00,27792.000000,0.022425,2024-12-31 16:54:45,2024-12-31 00:00:00,16.000000
max,138.252900,56.130400,1.032271e+06,4.430104e+06,981669.000000,304982.000000,232658.000000,0.269302,5.282874e+06,5.474756e+06,1.998724e+06,134139.000000,0.030000,2025-05-01 17:08:00,2025-05-01 00:00:00,19.000000
std,90.524261,29.330102,1.291954e+05,9.118957e+05,168758.692721,53459.056398,39801.207862,0.054360,1.096433e+06,9.587711e+05,3.198539e+05,21840.899426,0.005015,NaN,NaN,2.988543

In [6]:
df.isnull().sum()

Post_ID                  0
Platform                 0
Content_Type             0
Content_Category         0
Post_Type                0
Region                   0
Longitude                0
Latitude                 0
Engagement               0
Views                    0
Likes                    0
Shares                   0
Comments                 0
Engagement_Rate          0
Impressions              0
Video_Views              0
Live_Stream_Views        0
Clicks                3740
Click_Through_Rate    3740
Main_Hashtag             0
Post_Published_At        0
Post_Date                0
Post_Hour                0
Engagement_Level         0
dtype: int64

In [10]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns.tolist()

['post_id',
 'platform',
 'content_type',
 'content_category',
 'post_type',
 'region',
 'longitude',
 'latitude',
 'engagement',
 'views',
 'likes',
 'shares',
 'comments',
 'engagement_rate',
 'impressions',
 'video_views',
 'live_stream_views',
 'clicks',
 'click_through_rate',
 'main_hashtag',
 'post_published_at',
 'post_date',
 'post_hour',
 'engagement_level']

In [21]:
df['month'] = df['post_date'].dt.month
df['day_of_week'] = df['post_date'].dt.day_name()
df['quarter'] = df['post_date'].dt.quarter
df.head()

,post_id,platform,content_type,content_category,post_type,region,longitude,latitude,engagement,views,...,live_stream_views,clicks,click_through_rate,main_hashtag,post_date,post_hour,engagement_level,month,day_of_week,quarter
0,Post_1,TikTok,Organic,Product Promotion,Video,UK,-3.4360,55.3781,54510,599342,...,0,16813.0,0.0248,#FeatureHighlight,2024-03-14,15,Low,3,Thursday,1
1,Post_2,Instagram,Organic,Product Promotion,Video,India,78.9629,20.5937,259440,1896301,...,0,NaN,NaN,#ProductDemo,2024-04-24,12,Medium,4,Wednesday,2
2,Post_3,X.com,Organic,Entertainment,Text,Brazil,-51.9253,-14.2350,14182,253052,...,0,NaN,NaN,#MemeMonday,2024-12-01,10,Low,12,Sunday,4
3,Post_4,Instagram,Organic,Entertainment,Carousel,Australia,133.7751,-25.2744,49137,735640,...,0,NaN,NaN,#JustForFun,2024-07-07,12,Low,7,Sunday,3
4,Post_5,TikTok,Organic,Educational,Video,Brazil,-51.9253,-14.2350,20832,77358,...,0,1944.0,0.0209,#CaseStudy2025,2024-01-10,11,High,1,Wednesday,1

In [22]:
df.columns.tolist()

['post_id',
 'platform',
 'content_type',
 'content_category',
 'post_type',
 'region',
 'longitude',
 'latitude',
 'engagement',
 'views',
 'likes',
 'shares',
 'comments',
 'engagement_rate',
 'impressions',
 'video_views',
 'live_stream_views',
 'clicks',
 'click_through_rate',
 'main_hashtag',
 'post_date',
 'post_hour',
 'engagement_level',
 'month',
 'day_of_week',
 'quarter']

In [24]:
df.to_csv('social_media_cleaned.csv', index=False)
print("Cleaned dataset saved as 'social_media_cleaned.csv'")

Cleaned dataset saved as 'social_media_cleaned.csv'

In [25]:
! pip install pyodbc sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\duc.desktop-59niijt\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------- ----- 1.8/2.1 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.5 MB/s  0:00:00
Downloading greenlet-3.5.0-cp314-cp314-win_amd64.whl (239 kB)
Installing collected packages: pyodbc, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.0 pyodbc-5.3.0 sqlalchemy-2.0.49

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip